name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to server
      run: echo ${{ secrets.SSH_PRIVATE_KEY }} > /tmp/ssh-private-key ; rsync -avze "ssh -i /tmp/ssh-private-key" build/ ${{ secrets.USERNAME }}@${{ secrets.IP_ADDRESS }}:~/public_html
      env:
        SSH_AUTH_SOCK: /tmp/ssh-auth.sock
